services:
  parser-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - snippet-searcher-network

networks:
  snippet-searcher-network:
    external: true