services:
  parser-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      GITHUB_ACTOR: ${GITHUB_ACTOR}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      REDIS_HOST: event-bus
      REDIS_PORT: 6379
    depends_on:
      - redis

  api:
    container_name: "asset-service"
    image: ghcr.io/austral-ingsis/snippet-asset-service:latest
    ports:
      - "8082:8080"
    environment:
      AZURE_HOST: "http://azurite"
      NEW_RELIC_APP_NAME: "asset-service"
      NEW_RELIC_AGENT_ENABLED: false

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: "azurite"
    hostname: azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - blob:/workspace

  redis:
    container_name: "event-bus"
    image: redis:6-alpine
    ports:
      - "6379:6379"

volumes:
    blob: