services:
  db:
    image: postgres:14
    container_name: parser-postgres
    ports:
      - '5432:5432'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      POSTGRES_USER: 'your_username'
      POSTGRES_PASSWORD: 'your_password'
      POSTGRES_DB: 'your_database'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: