name: Verify CI

on:
  push:
    branches:
      - 'dev'
      - 'main'

jobs:
  verify_valid:
    name: Verify valid image
    uses: PrintScript8/ingsis-library/.github/workflows/on-pull-request.yml@main

  publish_docker:
    name: Publish Docker image
    needs: verify_valid
    uses: PrintScript8/ingsis-library/.github/workflows/docker-image.yml@main
    with:
      service_name: ${{ github.ref == 'refs/heads/main' && 'parser' || 'parser-dev' }}

  rerun_image:
    name: Rerun Docker image
    needs: publish_docker
    uses: PrintScript8/ingsis-library/.github/workflows/vm-login.yml@main
    with:
      service_name: ${{ github.ref == 'refs/heads/main' && 'parser' || 'parser-dev' }}
      port: "8081"
      is_dev: ${{ github.ref == 'refs/heads/dev' }}
      is_image: true
env:
  SSH_HOST_DEV: ${{ secrets.SSH_HOST_DEV }}
  SSH_USER_DEV: ${{ secrets.SSH_USER_DEV }}
  SSH_KEY_DEV: ${{ secrets.SSH_KEY_DEV }}



permissions:
  packages: write
